#!/bin/bash
if [ "$1" = "--version" ]; then
  echo "pylint 3.3.3"
  echo "astroid 3.3.8"
  echo "Python 3.11.2 (main, Sep 14 2024, 03:00:30) [GCC 12.2.0]"
else
  for last; do true; done
  filename=$(basename "$last")
  # Let's extract original filename from temp file's name, e.g. pycharm_pylint_15708631520625806318_d.py -> d.py
  filename="${filename/pycharm_pylint_/}"
  filename="${filename//[0-9]/}"
  filename="${filename/_/}"
  cat "$0_${filename}_result.json"
fi